// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSales.Data;

namespace WebSales.Migrations
{
    [DbContext(typeof(WebSalesContext))]
    [Migration("20241222175158_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebSales.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WebSales.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("SellId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("SellId");

                    b.ToTable("SalesRecord");
                });

            modelBuilder.Entity("WebSales.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("DepId");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("WebSales.Models.SalesRecord", b =>
                {
                    b.HasOne("WebSales.Models.Seller", "Sell")
                        .WithMany("Sales")
                        .HasForeignKey("SellId");
                });

            modelBuilder.Entity("WebSales.Models.Seller", b =>
                {
                    b.HasOne("WebSales.Models.Department", "Dep")
                        .WithMany("Sellers")
                        .HasForeignKey("DepId");
                });
#pragma warning restore 612, 618
        }
    }
}
